on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: check_as_cran

jobs:
  check_as_cran:
    # shell needs to use login mode so conda env activation can work
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: ubuntu-22.04, r: 'release'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          _R_CHECK_CRAN_INCOMING_: false
          NOT_CRAN: false
